export * from './api';
export * as authService from './auth';
export * as organizacaoService from './organizacao';
export * as membrosService from './membros';
export * as escalaFixaService from './escalaFixa';
export * as excecoesService from './excecoes';
export * as escalaVocalService from './escalaVocal';
export * as repertorioService from './repertorio';
export * as ministeriosService from './ministerios';
export * as comentariosService from './comentarios';
